# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.x

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      ### Bonsai bleeding release is currently broken
      # - name: Set up source repos
      #   run: |
      #     opam repo add janestreet-bleeding https://ocaml.janestreet.com/opam-repository
      #     opam repo add janestreet-bleeding-external https://github.com/janestreet/opam-repository.git#external-packages
      #     eval $(opam env)

      - name: Install Deps
        run: |
          opam install --yes . src/todo_list/0_hello_world
          eval $(opam env)

      - name: Build
        run: opam exec -- dune build

      - name: Format
        run: opam exec -- dune build @fmt

      - name: Test
        run: opam exec -- dune test

      - name: Assert generated matches
        run: |
          ./regen_clean.sh
          git diff-files --quiet
